 CREATE DATABASE QUANLYQUAYTHUOC
GO
USE QUANLYQUAYTHUOC
GO

CREATE TABLE NHANVIEN(
	MANV VARCHAR(10),
	TEN NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH BIT,
	CMND VARCHAR(12),
	SDT VARCHAR(10),
	DIACHI NVARCHAR(50),
	NGAYVAOLAM DATE,
	LUONG DECIMAL(10,0),
	CO_TK BIT,
	PHANQUYEN INT,
	FLAG_LAM BIT DEFAULT 1,
	
	PRIMARY KEY(MANV)
)
GO
CREATE TABLE KHACHHANG(
	MAKH VARCHAR(10),
	TENKH NVARCHAR(50),

	PRIMARY KEY(MAKH)
)
GO
CREATE TABLE TAIKHOAN(
	MANV VARCHAR(10) FOREIGN KEY REFERENCES NHANVIEN(MANV),
	TENDN VARCHAR(30),
	MATKHAU VARCHAR(30),

	PRIMARY KEY(TENDN)
)
GO

CREATE TABLE NHACUNGCAP(
	MANCC VARCHAR(10),
	TENNCC NVARCHAR(50),
	SDT VARCHAR(10),
	DIACHI NVARCHAR(50),

	PRIMARY KEY(MANCC)	
)
GO

CREATE TABLE SANPHAM(
	MASP INT IDENTITY(1,1),
	MANCC VARCHAR(10) FOREIGN KEY REFERENCES NHACUNGCAP(MANCC),
	TENSP NVARCHAR(50),
	LOAISP NVARCHAR(50),
	HINHANH IMAGE,
	DVT NVARCHAR(20),
	GIABAN DECIMAL(10,0),
	GIANHAP DECIMAL(10,0),
	SL INT,
	MOTA NVARCHAR(100),

	PRIMARY KEY(MASP)
)
GO

CREATE TABLE DONNHAPHANG(
	MADN INT IDENTITY(1,1),
	MANV VARCHAR(10) FOREIGN KEY REFERENCES NHANVIEN(MANV),
	NGAYNHAP DATE,
	NGAYGIAO DATE,
	TONGTIEN DECIMAL(10,0),
	TRANGTHAI BIT,

	PRIMARY KEY(MADN)
)
GO

CREATE TABLE CHITIETNHAPHANG(
	MADN INT FOREIGN KEY REFERENCES DONNHAPHANG(MADN),
	MASP INT FOREIGN KEY REFERENCES SANPHAM(MASP),
	SL INT,

	PRIMARY KEY(MADN, MASP)
)
GO

CREATE TABLE HOADONBANHANG(
	MAHD INT IDENTITY(1,1),
	MANV VARCHAR(10) FOREIGN KEY REFERENCES NHANVIEN(MANV),
	MAKH VARCHAR(10) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	NGAYLAP DATE,
	TONGTIEN DECIMAL(10, 0),
	TRANGTHAI BIT,

	PRIMARY KEY(MAHD)
)
GO

CREATE TABLE CHITIETHOADON(
	MAHD INT FOREIGN KEY REFERENCES HOADONBANHANG(MAHD),
	MASP INT FOREIGN KEY REFERENCES SANPHAM(MASP),
	SL INT,
	PRIMARY KEY(MAHD, MASP)
)
GO
--FUNCTION
CREATE FUNCTION TONGDOANHTHU(@NGAY DATE)
RETURNS DECIMAL(10, 0)
AS
BEGIN
	DECLARE @TONG DECIMAL(10, 0)
	SET @TONG = (SELECT SUM(TONGTIEN) FROM HOADONBANHANG WHERE NGAYLAP = @NGAY)
	RETURN @TONG
END
GO

--PROCEDURE

-- Đăng nhập
CREATE PROC USER_LOGIN
	@username VARCHAR(30),
	@password VARCHAR(30)
AS
BEGIN
	SET NOCOUNT ON
	SELECT * FROM TAIKHOAN
		WHERE TENDN = @username and MATKHAU =  @password
END
GO
-- Lấy thông tin nhân viên bằng Mã nhân viên
CREATE PROC GET_USER_BY_ID
	@maNhanVien VARCHAR(10)
AS
BEGIN
	SELECT * FROM NHANVIEN WHERE MANV = @maNhanVien
END
GO
-- Lấy thông tin nhân viên bằng Tên đăng nhập và mật khẩu
CREATE PROC GET_USER_BY_USERNAME_PASSWORD
	@username VARCHAR(30),
	@password VARCHAR(30)
AS
BEGIN
	SELECT * FROM NHANVIEN WHERE MANV = (SELECT MANV FROM TAIKHOAN WHERE TENDN = @username AND MATKHAU = @password)
END
GO
--LẤY THÔNG TIN SẢN PHẨM BẰNG MÃ SẢN PHẨM
CREATE PROC GET_PRODUCT_BY_ID
	@masp INT
AS
BEGIN
	SELECT * FROM SANPHAM WHERE MASP = @masp
END
GO
-- Lấy danh sách sản phẩm bán
CREATE PROC GET_PRODUCT_FOR_SALE
AS
BEGIN
	SELECT * FROM SANPHAM WHERE SL > 0
END
GO
-- Lấy danh sách loại sản phẩm
CREATE PROC GET_PRODUCT_TYPE
AS
BEGIN
	SELECT DISTINCT LOAISP FROM SANPHAM
END
GO
-- LẤY DANH SÁCH SẢN PHẨM LỌC
CREATE PROC GET_PRODUCT_FILTER
	@maSanPham INT, 
	@tenSanPham NVARCHAR(50), 
	@loaiSanPham NVARCHAR(50), 
	@tenNhaCungCap NVARCHAR(50)
AS
BEGIN
	SELECT * FROM SANPHAM WHERE MASP = @maSanPham OR TENSP LIKE @tenSanPham OR LOAISP LIKE @loaiSanPham OR MANCC IN (SELECT MANCC FROM NHACUNGCAP WHERE TENNCC LIKE @tenNhaCungCap)
END
GO
-- PROC LAY DANH SACH HOA DON
CREATE PROC GET_INVOICE_ALL
AS
BEGIN
	SELECT * FROM HOADONBANHANG
END
GO
--PROC TRA VE HOA DON CUOI CUNG
CREATE PROC GET_INVOICE_LAST
AS
BEGIN
	SELECT TOP(1) * FROM HOADONBANHANG ORDER BY MAHD DESC
END
GO

--PROC TRA VE DANH SACH KHACH HANG
CREATE PROC GET_CUSTOMER_ALL
AS
BEGIN
	SELECT * FROM KHACHHANG
END
GO

--PROC TRA VE KHACH HANG CAN TIM
CREATE PROC GET_CUSTOMER_ID 
	@MAKH VARCHAR(10)
AS
BEGIN
	SELECT * FROM KHACHHANG WHERE MAKH = @MAKH
END
GO

--PROC LAY KHACH HANG O CUOI DANH SACH
CREATE PROC GET_CUSTOMER_LAST
AS
BEGIN
	SELECT TOP(1) * FROM KHACHHANG ORDER BY MAKH DESC
END
GO

--PROC LAY KHACH HANG THEO TEN
CREATE PROC GET_CUSTOMER_NAME @TENKH VARCHAR(50)
AS
BEGIN
	SELECT * FROM KHACHHANG WHERE TENKH = @TENKH
END
GO

-- TÌM ADMIN CUỐI CÙNG
CREATE PROC GET_ADMIN_LAST
AS
BEGIN
	SELECT * FROM NHANVIEN WHERE PHANQUYEN = 0 ORDER BY MANV DESC
END
GO

-- TÌM USER CUỐI CÙNG
CREATE PROC GET_USER_LAST
AS
BEGIN
	SELECT * FROM NHANVIEN WHERE PHANQUYEN = 1 ORDER BY MANV DESC
END
GO

--PROC CAP NHAT SO LUONG DA BAN
CREATE PROC UPDATE_PRODUCT_AMOUNT 
	@MASP INT, 
	@SL INT
AS
BEGIN
	UPDATE SANPHAM SET SL = SL - @SL WHERE MASP = @MASP
END
GO

-- PROC LAY TONG DOANH THU THEO NGAY
CREATE PROC TONGTHUNHAP @NGAY DATE
AS
BEGIN
	SELECT SUM(TONGTIEN) AS TONG FROM HOADONBANHANG WHERE NGAYLAP = @NGAY
END
GO
-- PROC LAY TONG CHI THEO NGAY
CREATE PROC TONGCHI @NGAY DATE
AS
BEGIN
	SELECT SUM(TONGTIEN) AS TONG FROM DONNHAPHANG WHERE NGAYNHAP = @NGAY
END
GO

CREATE PROC GET_INVOICE_DETAIL_BY_ID
	@maHoaDon INT
AS
BEGIN 
	SELECT CT.MASP, SP.TENSP, CT.SL, SP.GIABAN  FROM HOADONBANHANG AS HD, CHITIETHOADON AS CT, SANPHAM AS SP
		WHERE HD.MAHD = @maHoaDon AND HD.MAHD = CT.MAHD AND CT.MASP = SP.MASP
END
GO

-- PROC THEM NHAN VIEN
CREATE PROCEDURE THEMNHANVIEN
	@MANV VARCHAR(10),
	@TEN NVARCHAR(50),
	@NGAYSINH DATE,
	@GIOITINH BIT,
	@CMND VARCHAR(12),
	@SDT VARCHAR(10),
	@DIACHI NVARCHAR(50),
	@NGAYVAOLAM DATE,
	@LUONG DECIMAL(10, 0),
	@PHANQUYEN INT
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANV OR CMND = @CMND OR SDT = @SDT)
	BEGIN
		INSERT INTO NHANVIEN VALUES(@MANV, @TEN, @NGAYSINH, @GIOITINH, @CMND, @SDT, @DIACHI, @NGAYVAOLAM, @LUONG, 0, @PHANQUYEN, 1)
	END
END
GO

--PROC THEM TAI KHOAN
CREATE PROC THEMTAIKHOAN
	@MANV VARCHAR(10),
	@TENDN VARCHAR(30),
	@MATKHAU VARCHAR(30)
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM TAIKHOAN WHERE MANV = @MANV OR TENDN = @TENDN)
	BEGIN
		INSERT INTO TAIKHOAN VALUES (@MANV, @TENDN, @MATKHAU)

		UPDATE NHANVIEN SET CO_TK = 1 WHERE MANV = @MANV
	END
END
GO

--PROC THEM KHACH HANG
-- 1
CREATE PROC THEMKHACHHANG
	@MAKH VARCHAR(10),
	@TENKH NVARCHAR(50)
AS
BEGIN
	IF NOT EXISTS(SELECT MAKH FROM KHACHHANG WHERE MAKH = @MAKH)
	BEGIN
		INSERT INTO KHACHHANG VALUES(@MAKH, @TENKH)
	END
END
GO

-- 2
CREATE PROC ADD_CUSTOMER
	@maKhachHang VARCHAR(10),
	@tenKhachHang NVARCHAR(50)
AS
BEGIN
	INSERT INTO KHACHHANG VALUES(@maKhachHang, @tenKhachHang)
END
GO

--PROC THEM NHA CUNG CAP
CREATE PROC THEMNHACUNGCAP
	@MANCC VARCHAR(10),
	@TENNCC NVARCHAR(50),
	@SDT VARCHAR(10),
	@DIACHI NVARCHAR(50)
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM NHACUNGCAP WHERE MANCC = @MANCC OR SDT = @SDT)
	BEGIN
		INSERT INTO NHACUNGCAP VALUES(@MANCC, @TENNCC, @SDT, @DIACHI)
	END
	--THIEU ELSE
END
GO

--PROC THEM SAN PHAM
CREATE PROC THEMSANPHAM
	@TENNCC VARCHAR(50),
	@TENSP NVARCHAR(50),
	@LOAISP NVARCHAR(50),
	@HINHANH IMAGE,
	@DVT NVARCHAR(20),
	@GIABAN DECIMAL(10, 0),
	@GIANHAP DECIMAL(10, 0),
	@SL INT,
	@MOTA NVARCHAR(100)
AS
BEGIN
	DECLARE @MANCC VARCHAR(10)
	SET @MANCC = (SELECT MANCC FROM NHACUNGCAP WHERE TENNCC = @TENNCC)
	INSERT INTO SANPHAM VALUES (@MANCC, @TENSP, @LOAISP, @HINHANH, @DVT, @GIABAN, @GIANHAP, @SL, @MOTA)
END
GO

--PROC THEM DON NHAP HANG
CREATE PROC THEMDONHAP
	@MANV VARCHAR(10),
	@NGAYNHAP DATE,
	@NGAYGIAO DATE,
	@TONGTIEN DECIMAL(10, 0),
	@TRANGTHAI BIT
AS
BEGIN
	INSERT INTO DONNHAPHANG VALUES(@MANV, @NGAYNHAP, @NGAYGIAO, @TONGTIEN, @TRANGTHAI)
END
GO

--PROC THEM CHI TIET NHAP HANG
CREATE PROC THEMCTNH
	@MASP INT,
	@SL INT
AS
BEGIN
	DECLARE @MADN INT
	SET @MADN = (SELECT TOP(1) MADN FROM DONNHAPHANG ORDER BY MADN DESC)
	INSERT INTO CHITIETNHAPHANG VALUES(@MADN, @MASP, @SL)
END
GO

--PROC THEM HOA DON BAN HANG
-- => Đổi tên từ THEMHOADON -> GENERATE_INVOICE
CREATE PROC GENERATE_INVOICE
	@MANV VARCHAR(10),
	@MAKH VARCHAR(10),
	@NGAYLAP DATE,
	@TONGTIEN DECIMAL(10, 0)
AS
BEGIN
	INSERT INTO HOADONBANHANG VALUES(@MANV, @MAKH, @NGAYLAP, @TONGTIEN, 1)
END
GO

--PROC THEM CHI TIET HOA DON
-- => Đổi tên từ THEMCTHD -> ADD_INVOICE_DETAIL
CREATE PROC ADD_INVOICE_DETAIL
	@MAHD INT,
	@MASP INT,
	@SL INT
AS
	BEGIN
		INSERT INTO CHITIETHOADON VALUES(@MAHD, @MASP, @SL)
	END
GO

--PROC DOI MAT KHAU
CREATE PROC DOIMK
	@TENDN VARCHAR(30),
	@MKCu VARCHAR(30),
	@MK_NEW VARCHAR(30)
	AS
BEGIN
	IF EXISTS(SELECT * FROM TAIKHOAN WHERE TENDN = @TENDN)
	BEGIN
		UPDATE TAIKHOAN
		SET MATKHAU = @MK_NEW
		WHERE TENDN = @TENDN
		AND MATKHAU = @MKCu
	END
	--THIEU ELSE
END
GO

--PROC DANH SACH NHAN VIEN
CREATE PROC DS_NV
AS
BEGIN
	SELECT * FROM NHANVIEN
END
GO

--PROC DANH SACH TAI KHOAN
CREATE PROC DS_TK
AS
BEGIN
	SELECT * FROM TAIKHOAN
END
GO

--PROC DANH SACH NHA CUNG CAP
CREATE PROC GET_NHACUNGCAP_ALL
AS
BEGIN
	SELECT * FROM NHACUNGCAP
END
GO

--PROC DANH SACH SAN PHAM
CREATE PROC DS_SP
AS
BEGIN
	SELECT * FROM SANPHAM
END
GO

--PROC DANH SACH DON NHAP
CREATE PROC DS_DN
AS
BEGIN
	SELECT * FROM DONNHAPHANG
END
GO

--PROC DANH SACH HOA DON BAN
CREATE PROC DS_HD
AS
BEGIN
	SELECT MAHD, MANV, TENKH, NGAYLAP, TONGTIEN, TRANGTHAI FROM HOADONBANHANG, KHACHHANG WHERE HOADONBANHANG.MAKH = KHACHHANG.MAKH
END
GO

--PROC DANH SACH CHI TIET HOA DON THEO MAHD
CREATE PROC DS_CTHD
	@MAHD INT
AS
BEGIN
	SELECT A.MAHD, A.MASP, B.TENSP, A.SL FROM CHITIETHOADON AS A, SANPHAM AS B WHERE MAHD = @MAHD AND A.MASP = B.MASP
END
GO

--PROC DANH SACH CHI TIET DON NHAP
CREATE PROC DS_CTDN
	@MADN INT
AS
BEGIN
	SELECT A.MADN, A.MASP, B.TENSP, A.SL FROM CHITIETNHAPHANG AS A, SANPHAM AS B WHERE MADN = @MADN AND A.MASP = B.MASP
END
GO

--PROC THONG TIN NGUOI DUNG HIEN TAI
CREATE PROC TTND 
	@TENDN VARCHAR(30)
AS
BEGIN
	SELECT MANV,TEN,NGAYSINH,GIOITINH,CMND,SDT,DIACHI,NGAYVAOLAM,LUONG,PHANQUYEN FROM NHANVIEN WHERE MANV IN (SELECT MANV FROM TAIKHOAN WHERE TENDN = @TENDN)
END
GO

--PROC TOM TAC DANH SACH SAN PHAM
CREATE PROC DS_NH
AS
BEGIN
	SELECT MASP, MANCC, TENSP, LOAISP, DVT, GIANHAP, MOTA FROM SANPHAM
END
GO

--PROC CAP NHAT THONG TIN CA NHAN
CREATE PROC CAPNHATTTCB
	@MANV VARCHAR(10),
	@TEN NVARCHAR(50),
	@NGAYSINH DATE,
	@GIOITINH BIT,
	@CMND VARCHAR(12),
	@SDT VARCHAR(10),
	@DIACHI NVARCHAR(50)
AS
BEGIN
	IF EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV = @MANV)
	BEGIN
		UPDATE NHANVIEN SET TEN = @TEN, NGAYSINH = @NGAYSINH, GIOITINH = @GIOITINH, CMND = @CMND, SDT = @SDT, DIACHI = @DIACHI
						WHERE MANV = @MANV
	END
END
GO

--PROC CAP NHAT NHAN VIEN 
CREATE PROCEDURE CAPNHATNHANVIEN
	@MANV VARCHAR(10),
	@TEN NVARCHAR(50),
	@NGAYSINH DATE,
	@GIOITINH BIT,
	@CMND VARCHAR(12),
	@SDT VARCHAR(10),
	@DIACHI NVARCHAR(50),
	@NGAYVAOLAM DATE,
	@LUONG DECIMAL(10, 0),
	@CO_TK BIT,
	@PHANQUYEN BIT,
	@FLAG_LAM BIT
AS
BEGIN
	IF EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV = @MANV)
	BEGIN
		UPDATE NHANVIEN SET TEN = @TEN, NGAYSINH = @NGAYSINH, GIOITINH = @GIOITINH, CMND = @CMND, SDT = @SDT, DIACHI = @DIACHI, NGAYVAOLAM = @NGAYVAOLAM, LUONG = @LUONG, CO_TK = @CO_TK, PHANQUYEN = @PHANQUYEN, FLAG_LAM = @FLAG_LAM
						WHERE MANV = @MANV
	END
	--THIEU ELSE
END
GO

--PROC CAP NHAT TAI KHOAN
CREATE PROC CAPNHATTAIKHOAN
	@MANV VARCHAR(10),
	@TENDN VARCHAR(30),
	@MATKHAU VARCHAR(30)
AS
BEGIN
	IF EXISTS(SELECT * FROM TAIKHOAN WHERE MANV = @MANV AND TENDN = @TENDN)
	BEGIN
		UPDATE TAIKHOAN SET TENDN = @TENDN, MATKHAU = @MATKHAU
						WHERE MANV = @MANV
	END
	--THIEU ELSE
END
GO

--PROC CAP NHAT KHACH HANG
CREATE PROC CAPNHATKHACHHANG
	@MAKH VARCHAR(10),
	@TENKH NVARCHAR(50)
AS
BEGIN
	IF EXISTS(SELECT MAKH FROM KHACHHANG WHERE MAKH = @MAKH)
	BEGIN
		UPDATE KHACHHANG SET TENKH = @TENKH
						 WHERE MAKH = @MAKH
	END
	--THIEU ELSE
END
GO

--PROC CAP NHAT NHA CUNG CAP
CREATE PROC CAPNHATNHACUNGCAP
	@MANCC VARCHAR(10),
	@TENNCC NVARCHAR(50),
	@SDT VARCHAR(10),
	@DIACHI NVARCHAR(50)
AS
BEGIN
	IF EXISTS(SELECT * FROM NHACUNGCAP WHERE MANCC = @MANCC)
	BEGIN
		UPDATE NHACUNGCAP SET TENNCC = @TENNCC, SDT = @SDT, DIACHI = @DIACHI
						  WHERE MANCC = @MANCC
	END
	--THIEU ELSE
END
GO

--PROC THEM SAN PHAM
CREATE PROC CAPNHATSANPHAM
	@MASP INT,
	@MANCC VARCHAR(10),
	@TENSP NVARCHAR(50),
	@LOAISP NVARCHAR(50),
	@HINHANH IMAGE,
	@DVT NVARCHAR(20),
	@GIABAN DECIMAL(10, 0),
	@GIANHAP DECIMAL(10, 0),
	@SL INT,
	@MOTA NVARCHAR(100)
AS
BEGIN
	IF EXISTS(SELECT * FROM SANPHAM WHERE MASP = @MASP)
	BEGIN
		UPDATE SANPHAM SET MANCC = @MANCC, TENSP = @TENSP, LOAISP = @LOAISP, HINHANH = @HINHANH, DVT = @DVT, GIABAN = @GIABAN, GIANHAP = @GIANHAP, SL = @SL, MOTA = @MOTA
					   WHERE MASP = @MASP
	END
	--THIEU ELSE
END
GO

--PROC CAP NHAT DON NHAP HANG
CREATE PROC CAPNHATDONHAP
	@MADN INT,
	@MANV VARCHAR(10),
	@NGAYNHAP DATE,
	@NGAYGIAO DATE,
	@TONGTIEN DECIMAL(10, 0),
	@TRANGTHAI BIT
AS
BEGIN
	IF EXISTS(SELECT * FROM DONNHAPHANG WHERE MADN = @MADN)
	BEGIN
		DECLARE @STT INT, @TT BIT, @COUNT INT, @SL INT
		SET @TT = (SELECT TRANGTHAI FROM DONNHAPHANG WHERE MADN = @MADN)
		SET @COUNT = (SELECT COUNT(*) FROM SANPHAM)

		IF @TT = 0 AND @TRANGTHAI = 1
		BEGIN
			SET NOCOUNT ON
			SET @STT = 1
			WHILE (@STT <= @COUNT)
			BEGIN
				SET @SL = (SELECT CHITIETNHAPHANG.SL FROM CHITIETNHAPHANG, SANPHAM WHERE MADN = @MADN AND SANPHAM.MASP = CHITIETNHAPHANG.MASP AND SANPHAM.MASP = @STT)
				UPDATE SANPHAM SET SL = SL + (SELECT CASE WHEN @SL IS NOT NULL THEN @SL
														  ELSE 0 END)
								WHERE MASP = @STT
				SET @STT = @STT + 1
			END
		END
		IF @TT = 1 AND @TRANGTHAI = 0
		BEGIN
			SET NOCOUNT ON
			SET @STT = 1
			WHILE (@STT <= @COUNT)
			BEGIN
				SET @SL = (SELECT CHITIETNHAPHANG.SL FROM CHITIETNHAPHANG, SANPHAM WHERE MADN = @MADN AND SANPHAM.MASP = CHITIETNHAPHANG.MASP AND SANPHAM.MASP = @STT)
				UPDATE SANPHAM SET SL = SL - (SELECT CASE WHEN @SL IS NOT NULL THEN @SL
														  ELSE 0 END)
								WHERE MASP = @STT
				SET @STT = @STT + 1
			END
		END
		SET NOCOUNT OFF
		UPDATE DONNHAPHANG SET MANV = @MANV, NGAYNHAP = @NGAYNHAP, NGAYGIAO = @NGAYGIAO, TONGTIEN = @TONGTIEN, TRANGTHAI = @TRANGTHAI
						   WHERE MADN = @MADN
	END
	--THIEU ELSE 
END
GO

--PROC THEM CHI TIET NHAP HANG
CREATE PROC CAPNHATCTNH
	@MADN INT,
	@MASP INT,
	@SL INT
AS
BEGIN
	IF EXISTS(SELECT * FROM CHITIETNHAPHANG WHERE MADN = @MADN)
	BEGIN
		UPDATE CHITIETNHAPHANG SET MASP = @MASP, SL = @SL
							   WHERE MADN = @MADN
	END
	--THIEU ELSE
END
GO

--PROC THEM HOA DON BAN HANG
CREATE PROC CAPNHATHOADON
	@MAHD INT,
	@MANV VARCHAR(10),
	@TENKH VARCHAR(50),
	@NGAYLAP DATE,
	@TONGTIEN DECIMAL(10, 0),
	@TRANGTHAI BIT
AS
BEGIN
	IF EXISTS(SELECT * FROM HOADONBANHANG WHERE MAHD = @MAHD)
	BEGIN
		UPDATE HOADONBANHANG SET MANV = @MANV, NGAYLAP = @NGAYLAP, TONGTIEN = @TONGTIEN, TRANGTHAI = @TRANGTHAI
							 WHERE MAHD = @MAHD
		DECLARE @MAKH VARCHAR(10)
		SET @MAKH = (SELECT MAKH FROM HOADONBANHANG WHERE MAHD = @MAHD)
		UPDATE KHACHHANG SET TENKH = @TENKH WHERE MAKH = @MAKH
	END
	--THIEU ELSE
END
GO

--PROC THEM CHI TIET HOA DON
CREATE PROC CAPNHATCTHD
	@MAHD INT,
	@MASP INT,
	@SL INT
AS
BEGIN
	IF EXISTS(SELECT * FROM CHITIETHOADON WHERE MAHD = @MAHD)
	BEGIN
		UPDATE CHITIETHOADON SET MASP = @MASP, SL = @SL
							 WHERE MAHD = @MAHD
	END
	--THIEU ELSE
END
GO

--PROC XOA NHAN VIEN
CREATE PROC XOANHANVIEN
	@MANV VARCHAR(10)
AS
BEGIN
	UPDATE NHANVIEN SET FLAG_LAM = 0
END
GO

--PROC XOA TAI KHOAN
CREATE PROC XOATAIKHOAN
	@MANV VARCHAR(10),
	@TENDN VARCHAR(30)
AS
BEGIN
	DELETE FROM TAIKHOAN
	WHERE MANV = @MANV AND TENDN = @TENDN
END
GO

--PROC XOA KHACH HANG
CREATE PROC XOAKHACHHANG
	@MAKH VARCHAR(10)
AS
BEGIN
	DELETE FROM KHACHHANG
	WHERE MAKH = @MAKH
END
GO

--PROC XOA NHA CUNG CAP
CREATE PROC XOANCC
	@MANCC VARCHAR(10)
AS
BEGIN
	DELETE FROM NHACUNGCAP
	WHERE MANCC = @MANCC
END
GO

--PROC XOA SAN PHAM
CREATE PROC XOASANPHAM
	@MASP INT
AS
BEGIN
	DELETE FROM SANPHAM
	WHERE MASP = @MASP
END
GO

--PROC XOA DON NHAP HANG
CREATE PROC XOADONNHAP
	@MADN INT
AS
BEGIN
	DELETE FROM DONNHAPHANG
	WHERE MADN = @MADN
END
GO

--PROC XOA CHI TIET NHAP HANG
CREATE PROC XOACTNH
	@MADN INT
AS
BEGIN
	DELETE FROM DONNHAPHANG
	WHERE MADN = @MADN
END
GO

--PROC XOA HOA DON BAN HANG
CREATE PROC XOAHOADON
	@MAHD INT
AS
BEGIN
	DELETE FROM HOADONBANHANG
	WHERE MAHD = @MAHD
END
GO

--PROC XOA CHI TIET HOA DON
CREATE PROC XOACTHD
	@MAHD INT
AS
BEGIN
	DELETE FROM CHITIETHOADON
	WHERE MAHD = @MAHD
END
GO

SET DATEFORMAT DMY
GO
INSERT INTO NHANVIEN VALUES ('ADMIN00001',N'Nguyễn Huỳnh Tất Đạt','15/12/2001',0,'151200001512','0123456789',N'Củ Chi','1/1/2018',100000000,1,0,1)
GO
INSERT INTO TAIKHOAN VALUES ('ADMIN00001','TADAadmin','TADATADATADA')

GO
INSERT INTO NHACUNGCAP VALUES 
('NCC1','LongABC','0781422475','Bình Định'),
('NCC2','TADA','0564721474','TP.HCM'),
('NCC3','ThuocSell','0714224795','Long An')
GO

INSERT INTO SANPHAM VALUES
('NCC1',N'Hoạt Huyết',N'Thuốc Bổ',null,N'Hộp','45000','30000',50,''),
('NCC2','Panadol',N'Giảm đau',null,N'Hộp','80000','70000',50,''),
('NCC1','Vitamin C',N'Thuốc Bổ',null,N'Ống','60000','45000',50,'')
GO
INSERT INTO KHACHHANG VALUES
('KH1','NGUYEN VAN A'),
('KH2','NGUYEN VAN B'),
('KH3','NGUYEN VAN C')
GO
INSERT INTO HOADONBANHANG VALUES
('ADMIN00001','KH1','26/4/2021',0,1),
('ADMIN00001','KH2','26/4/2021',0,1),
('ADMIN00001','KH3','27/4/2021',0,1)
GO
INSERT INTO CHITIETHOADON VALUES
(1,1,3),
(2,2,2),
(3,1,4)
GO
INSERT INTO DONNHAPHANG VALUES
('ADMIN00001','26/4/2021','27/4/2021','450000',1),
('ADMIN00001','25/4/2021','26/4/2021','300000',1)
GO
INSERT INTO CHITIETNHAPHANG VALUES
(2,1,30),
(1,2,15)
GO
